language: python

dist: xenial

matrix:
  include:
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      script: python3 -m pytest
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install -r requirements.txt

script: pytest
