language: python

matrix:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      script: python3 -m pytest

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install -r requirements.txt

script: pytest
